# docker-compose.yml
version: '3.8'

services:
  frontend:
    build: .
    container_name: fullstackapp-frontend
    environment:
      - NODE_ENV=development
    command: npm run dev
    ports:
      - "3000:3000"